INSERT INTO DEPARTMENTS (ID,NAME) VALUES (NEXTVAL('DEPARTMENTS_SEQ'),'R&D');
INSERT INTO DEPARTMENTS (ID,NAME) VALUES (NEXTVAL('DEPARTMENTS_SEQ'),'Sales');
INSERT INTO DEPARTMENTS (ID,NAME) VALUES (NEXTVAL('DEPARTMENTS_SEQ'),'HR');
INSERT INTO DEPARTMENTS (ID,NAME) VALUES (NEXTVAL('DEPARTMENTS_SEQ'),'Production');