DROP TABLE IF EXISTS DEPARTMENTS;
DROP TABLE IF EXISTS WORKERS;
DROP SEQUENCE IF EXISTS DEPARTMENTS_SEQ;
DROP SEQUENCE IF EXISTS WORKERS_SEQ;

CREATE SEQUENCE DEPARTMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE WORKERS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE DEPARTMENTS(
  ID INT8 default DEPARTMENTS_SEQ.nextval,
  NAME varchar(255) not null,
  primary key(ID)
);

CREATE TABLE WORKERS
(
   ID INT8 not null,
   FIRST_NAME varchar (255) not null,
   LAST_NAME varchar(255) not null,
   PHONE_NUMBER varchar(255),
   DEPARTMENT_ID INT8,
   primary key(ID),
   foreign key (DEPARTMENT_ID) references DEPARTMENTS(ID)
);

ALTER TABLE WORKERS
  ADD CONSTRAINT uq_names UNIQUE(FIRST_NAME, LAST_NAME);