//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 01:46:53 AM MSK 
//


package com.ikhramchenkov.staffmanagement.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Worker" type="{http://ikhramchenkov.com/staffmanagement/jaxb/}WorkerEntity"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "worker"
})
@XmlRootElement(name = "EditWorkerRequest")
public class EditWorkerRequest {

    @XmlElement(name = "Worker", required = true)
    protected WorkerEntity worker;

    /**
     * Gets the value of the worker property.
     * 
     * @return
     *     possible object is
     *     {@link WorkerEntity }
     *     
     */
    public WorkerEntity getWorker() {
        return worker;
    }

    /**
     * Sets the value of the worker property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkerEntity }
     *     
     */
    public void setWorker(WorkerEntity value) {
        this.worker = value;
    }

}
