//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 01:46:53 AM MSK 
//


package com.ikhramchenkov.staffmanagement.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ikhramchenkov.staffmanagement.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ikhramchenkov.staffmanagement.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EditWorkerRequest }
     * 
     */
    public EditWorkerRequest createEditWorkerRequest() {
        return new EditWorkerRequest();
    }

    /**
     * Create an instance of {@link WorkerEntity }
     * 
     */
    public WorkerEntity createWorkerEntity() {
        return new WorkerEntity();
    }

    /**
     * Create an instance of {@link GetStaffResponse }
     * 
     */
    public GetStaffResponse createGetStaffResponse() {
        return new GetStaffResponse();
    }

    /**
     * Create an instance of {@link WorkerWithDepartmentEntity }
     * 
     */
    public WorkerWithDepartmentEntity createWorkerWithDepartmentEntity() {
        return new WorkerWithDepartmentEntity();
    }

    /**
     * Create an instance of {@link AssignWorkerRequest }
     * 
     */
    public AssignWorkerRequest createAssignWorkerRequest() {
        return new AssignWorkerRequest();
    }

    /**
     * Create an instance of {@link AddWorkerRequest }
     * 
     */
    public AddWorkerRequest createAddWorkerRequest() {
        return new AddWorkerRequest();
    }

    /**
     * Create an instance of {@link AddWorkerResponse }
     * 
     */
    public AddWorkerResponse createAddWorkerResponse() {
        return new AddWorkerResponse();
    }

    /**
     * Create an instance of {@link UnassignWorkerResponse }
     * 
     */
    public UnassignWorkerResponse createUnassignWorkerResponse() {
        return new UnassignWorkerResponse();
    }

    /**
     * Create an instance of {@link EditWorkerResponse }
     * 
     */
    public EditWorkerResponse createEditWorkerResponse() {
        return new EditWorkerResponse();
    }

    /**
     * Create an instance of {@link AssignWorkerResponse }
     * 
     */
    public AssignWorkerResponse createAssignWorkerResponse() {
        return new AssignWorkerResponse();
    }

    /**
     * Create an instance of {@link GetStaffRequest }
     * 
     */
    public GetStaffRequest createGetStaffRequest() {
        return new GetStaffRequest();
    }

    /**
     * Create an instance of {@link DeleteWorkerRequest }
     * 
     */
    public DeleteWorkerRequest createDeleteWorkerRequest() {
        return new DeleteWorkerRequest();
    }

    /**
     * Create an instance of {@link UnassignWorkerRequest }
     * 
     */
    public UnassignWorkerRequest createUnassignWorkerRequest() {
        return new UnassignWorkerRequest();
    }

    /**
     * Create an instance of {@link DeleteWorkerResponse }
     * 
     */
    public DeleteWorkerResponse createDeleteWorkerResponse() {
        return new DeleteWorkerResponse();
    }

    /**
     * Create an instance of {@link DepartmentEntity }
     * 
     */
    public DepartmentEntity createDepartmentEntity() {
        return new DepartmentEntity();
    }

}
